### ISSUE TITLE
Unable to parse first sentence of The Wonderful Magician of Oz

### ISSUE THREAD

**Issue by yannis1962** [lojban/ilmentufa#27]
Hi,

ilmentufa worked for a relatively short text, but when I try with

**ni'o la .dorotis. cu xabju lo midju be lo ganra sastu'a pe la .kanzas. fi'o kansa la nakfamti .xenris. ku noi te cange ku'o .e la fetfamti .em. ku noi speni lo te cange**

I get the error message

```
ni'o la .dorotis. cu xabju lo midju be lo ganra sastu'a pe la .kanzas. fi'o kansa la nakfamti .xenris. ku noi te cange ku'o .e la fetfamti .em. ku noi speni lo te cange
 ^

SyntaxError: Unexpected token 'i', "ni'o la .do"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.camxes_postprocessing (/Users/yannis/Downloads/LIVRE/PYTHON/EXOS/03-4/ilmentufa-master/camxes_postproc.js:65:40)
    at run_camxes (/Users/yannis/Downloads/LIVRE/PYTHON/EXOS/03-4/ilmentufa-master/run_camxes.js:135:38)
    at Object.<anonymous> (/Users/yannis/Downloads/LIVRE/PYTHON/EXOS/03-4/ilmentufa-master/run_camxes.js:90:26)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.3.1

```
Do you know what I'm doing wrong?

**Comment by Ntsekees** [comment]
Sorry for the very belated reply, but I hadn't seen your message…
The sentence you've tried to input makes use of an experimental grammar feature called “cmevla-brivla merger” (abbreviated “CBM”), exemplified in the sentence by ⟪la nakfamti .xenris. ku⟫, which is not valid in standard Lojban.
On [this parser interface](https://lojban.github.io/ilmentufa/camxes.html), there's a dropdown menu labeled ⟪Parser⟫, which allows you to select one of several different parsers, each implementing different grammar features. In the case of your sentence, you should use the ⟪Camxes: Beta CBM⟫ parser, which can handle cmevla-brivla merger grammar.
I have checked, that parser is able to parse your sentence.
